"
The critique that explains you need to write tests for this class
"
Class {
	#name : #SmTClassNeedTestsCritique,
	#superclass : #SmTNeedTestsCritique,
	#category : #'SmartTest-Critiques'
}

{ #category : #accessing }
SmTClassNeedTestsCritique >> description [
	^'You should always write tests your classes to ensure the fiability of your code'
]

{ #category : #accessing }
SmTClassNeedTestsCritique >> title [
	^ 'You should write tests for your class'
]
