"
Data for SmartTest tests on the testForClass:.

Methods of this class have long name in order to be unique and explicit.
Being unique, the senders of each method are mastered and consequently the tests are independent the one from the others.

We will use this that to assert that SmartTest behaves correctly when dealing with inherited methods ans class.

This class is a subclass of TestCase and contains a test.
"
Class {
	#name : #SmTClassModificationOnClassSimpleTestCase,
	#superclass : #TestCase,
	#category : 'SmartTestDataOutsideP1-ModificationOnClass-Tests'
}

{ #category : #tests }
SmTClassModificationOnClassSimpleTestCase >> testModificationOnClassSimpleTestCase [
"The behaviour of this method is irrelevant."
]
