"
Data for SmartTest tests on the filters:.

Methods of this class have long name in order to be unique and explicit.
Being unique, the senders of each method are mastered and consequently the tests are independent the one from the others.

We will use this that to assert that SmartTest behaves correctly when dealing with inherited methods ans class.

This class inherits one test from its superior class and doesn't redefine it.
"
Class {
	#name : #SmTExtensionP1,
	#superclass : #Object,
	#category : 'SmartTestDataOutsideP1-ModificationOnMethod-SenderExtensionMethod'
}

{ #category : #'as yet unclassified' }
SmTExtensionP1 >> extensionMethod1SecondLevelSenders [
]
