SystemOrganization addCategory: #SmartTestDataOutsideP2!
SystemOrganization addCategory: #'SmartTestDataOutsideP2-References'!
SystemOrganization addCategory: #'SmartTestDataOutsideP2-SenderOutTestInWithRef'!
SystemOrganization addCategory: #'SmartTestDataOutsideP2-SenderOutTestOutWithRef'!
SystemOrganization addCategory: #'SmartTestDataOutsideP2-Tests'!
SystemOrganization addCategory: #'SmartTestDataOutsideP2-WithoutRef'!
SystemOrganization addCategory: #'SmartTestDataOutsideP2-extensionMethod'!
