SystemOrganization addCategory: #'SmartTest-Tests'!
SystemOrganization addCategory: #'SmartTest-Tests-Cache'!
SystemOrganization addCategory: #'SmartTest-Tests-CacheBuilder'!
SystemOrganization addCategory: #'SmartTest-Tests-Filter'!
SystemOrganization addCategory: #'SmartTest-Tests-Finder'!
SystemOrganization addCategory: #'SmartTest-Tests-OnModification'!
SystemOrganization addCategory: #'SmartTest-Tests-Runner'!
SystemOrganization addCategory: #'SmartTest-Tests-Settings'!
